[TAIPY]

[DATA_NODE.demand]
storage_type = "csv"
path = "data/time_series_demand.csv"
has_header = "True:bool"

[DATA_NODE.solver_name]
default_data = "Default"

[DATA_NODE.model_created]

[DATA_NODE.model_solved]

[DATA_NODE.results]

[TASK.create_model]
function = "algos.algos.create_model:function"
inputs = [ "demand:SECTION", "fixed_variables:SECTION",]
outputs = [ "model_created:SECTION",]
skippable = "False:bool"

[TASK.solve_model]
function = "algos.algos.solve_model:function"
inputs = [ "model_created:SECTION", "solver_name:SECTION",]
outputs = [ "model_solved:SECTION",]
skippable = "False:bool"

[TASK.create_results]
function = "algos.algos.create_results:function"
inputs = [ "model_solved:SECTION", "fixed_variables:SECTION", "demand:SECTION",]
outputs = [ "results:SECTION",]
skippable = "False:bool"

[SCENARIO.scenario]
tasks = [ "create_model:SECTION", "solve_model:SECTION", "create_results:SECTION",]
additional_data_nodes = []
frequency = "MONTHLY:FREQUENCY"

[DATA_NODE.fixed_variables.default_data]
Max_Capacity_FPA = "950:int"
cost_FPA_Back_Order = "200:int"
cost_FPA_Stock = "45:int"
Initial_Back_Order_FPA = "0:int"
Initial_Stock_FPA = "30:int"
Initial_Production_FPA = "850:int"
number_RPone_to_produce_FPA = "20:int"
number_RPtwo_to_produce_FPA = "15:int"
Max_Capacity_FPB = "950:int"
cost_FPB_Back_Order = "250:int"
cost_FPB_Stock = "40:int"
Initial_Back_Order_FPB = "25:int"
Initial_Stock_FPB = "0:int"
Initial_Production_FPB = "800:int"
number_RPone_to_produce_FPB = "50:int"
number_RPtwo_to_produce_FPB = "45:int"
Initial_Stock_RPone = "30:int"
Max_Stock_RPone = "80:int"
cost_RPone_Stock = "30:int"
cost_RPone_Purchase = "100:int"
Initial_Purchase_RPone = "35:int"
Initial_Stock_RPtwo = "40:int"
Max_Stock_RPtwo = "60:int"
cost_RPtwo_Stock = "60:int"
cost_RPtwo_Purchase = "150:int"
Initial_Purchase_RPtwo = "40:int"
Weight_of_Stock = "100:int"
Weight_of_Back_Order = "100:int"
Max_Capacity_of_FPA_and_FPB = "1710.0:float"

[SCENARIO.scenario.comparators]

[SCENARIO.scenario.sequences]
